# Generated by Django 3.0.6 on 2020-05-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='painting',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
