# Generated by Django 3.0.6 on 2020-05-21 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0002_painting_painting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='viewed',
        ),
        migrations.CreateModel(
            name='UserPainting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('painting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Painting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
