# Generated by Django 3.0.6 on 2020-05-21 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
