# Generated by Django 3.0.6 on 2020-05-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_attempt_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='first_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='second_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='third_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
