# Generated by Django 3.0.6 on 2020-05-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20200523_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
