# Generated by Django 3.0.6 on 2020-05-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='usemap',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
