# Generated by Django 3.0.6 on 2020-05-23 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_room_usemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaintingPerRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('painting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Painting')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Room')),
            ],
        ),
    ]
