# Generated by Django 3.0.6 on 2020-05-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_paintingperroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='usemap',
            new_name='room_id',
        ),
    ]
