# Generated by Django 3.0.6 on 2020-05-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20200523_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingperroom',
            name='href',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
