# Generated by Django 3.0.6 on 2020-05-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paintingperroom',
            name='href',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_id',
        ),
    ]
