# Generated by Django 3.0.6 on 2020-05-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20200524_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintingperroom',
            name='href',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
