# Generated by Django 3.0.6 on 2020-05-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200527_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Answer',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('answer', models.ManyToManyField(blank=True, null=True, to='adventure.Answer')),
                ('door', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Door')),
            ],
        ),
    ]
