# Generated by Django 3.0.6 on 2020-05-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_auto_20200527_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='door',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Question'),
        ),
    ]
