# Generated by Django 3.0.6 on 2020-05-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0006_auto_20200527_1026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Prompt',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='prompt',
        ),
    ]
