# Generated by Django 3.0.6 on 2020-05-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0009_result_preceding_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='door',
        ),
        migrations.RemoveField(
            model_name='result',
            name='prompt',
        ),
        migrations.AddField(
            model_name='prompt',
            name='count',
            field=models.CharField(blank=True, default='0', max_length=1000, null=True),
        ),
    ]
