# Generated by Django 3.0.6 on 2020-05-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0010_auto_20200527_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ultimate',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
