# Generated by Django 3.0.6 on 2020-05-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0012_auto_20200527_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='prompt',
            new_name='parent',
        ),
    ]
