# Generated by Django 3.0.6 on 2020-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0015_auto_20200527_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamber',
            name='door',
        ),
        migrations.AlterField(
            model_name='chamber',
            name='result',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
