# Generated by Django 3.0.6 on 2020-05-27 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0017_chamber_door'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Chamber')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.Option')),
            ],
        ),
    ]
