# Generated by Django 3.0.6 on 2020-05-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0018_previousoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previousoption',
            old_name='option',
            new_name='previous_option',
        ),
    ]
