# Generated by Django 3.0.6 on 2020-05-27 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0019_auto_20200527_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousoption',
            name='previous_chamber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_chamber', to='adventure.Chamber'),
        ),
    ]
