# Generated by Django 3.0.6 on 2020-05-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0020_previousoption_previous_chamber'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamber',
            name='initial_chamber',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
