# Generated by Django 3.0.6 on 2020-05-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0021_chamber_initial_chamber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previousoption',
            old_name='chamber',
            new_name='current_chamber',
        ),
    ]
